### PR TITLE
v1.0.0 Checklist

### PR DESCRIPTION
**Pull request by ericclemmons**
- [x] #9 – `terse-webpack` binary.
- [x] #10 – Embed `webpack@2`
- [x] #5 – Remove `.babel` as a default.
- [x] 45db434ad1a886eb3e553769a4be2e21c93d68ea – Remove `react` alias.
- [x] #3 – Include `eslint-loader` if `.eslintrc` is present.
- [x] 88c52a71390c437adf403969f619e471c1ac399d – Include `babel-loader` if `.babelrc` is present.
- [x] #2 – Add `npm-install-webpack-plugin`.
- [x] #5 – Add `.defaults()` option
- [x] ~~#14 – Replace HMR with latest beta: gaearon/react-hot-boilerplate#61~~
- [x] Fully functioning `example`.

### CODE REVIEW

**Comment by ericclemmons** [comment]
```js
// .babelrc
{
  "presets": ["es2015", "stage-1"]
}
```

```js
// webpack.config.babel.js
import client from "./webpack.config.client.babel.js";
import server from "./webpack.config.server.babel.js";

export default [
  client,
  server,
];
```

```js
// webpack.config.defaults.babel.js
import { Config } from "@terse/webpack";

export const babel = {
  cacheDirectory: true,
  presets: ["es2015-webpack", "react", "stage-1"],
  plugins: [
    "react-html-attrs",
    "transform-class-properties",
    "transform-decorators-legacy",
  ],
};

export default new Config()
  .alias("react")
  .loader("json", ".json")
  .loader("style", ".css")
  .loader("css", ".css", {
    query: {
      localIdentName: "[name]-[local]--[hash:base64:5]",
    },
  })
  .loader("style", ".less")
  .loader("css", ".less")
  .loader("less", ".less")
  .loader("url", [".woff", ".woff2"], {
    query: {
      mimetype: "application/font-woff",
    },
  })
  .loader("url", ".ttf", {
    query: {
      mimetype: "application/octet-stream",
    },
  })
  .loader("file", ".eot")
  .loader("url", ".svg", {
    query: {
      mimetype: "image/svg+xml",
    },
  })
  .loader("url", [".jpg", ".png"], {
    query: {
      limit: 8192, // Inline base64 URLs for <= 8K images
    },
  })
  .modules("./lib") // @TODO Convert to "paths"
  .when("development", (config) => config
    .devtool("cheap-module-eval-source-map")
    .plugin("webpack.HotModuleReplacementPlugin")
    .preLoader("eslint", ".js", {
      exclude: /node_modules/,
    })
  )
;
```

```js
// webpack.config.client.babel.js
import { ClientConfig } from "@terse/webpack";

import {
  babel,
  default as defaults,
} from "./webpack.config.defaults.babel";

module.exports = new ClientConfig()
  .apply(defaults)
  .entry("src/client.js", "src/widgets.js")
  .loader("babel", ".js", {
    include: "./node_modules/qs",
  })
  .loader("babel", ".js", {
    exclude: /node_modules/,
    query: {
      ...babel,
      env: {
        development: {
          plugins: [
            ["react-transform", {
              transforms: [{
                transform: "react-transform-hmr",
                imports: ["react"],
                locals: ["module"],
              }],
            }],
          ],
        },
      },
    },
  })
  .when("development", function(config) {
    return config
      .plugin("webpack.NoErrorsPlugin")
    ;
  })
  .toWebpack()
;
```

```js
// webpack.config.server.babel.js
import { ServerConfig } from "@terse/webpack";

import {
  babel,
  default as defaults,
} from "./webpack.config.defaults.babel";

module.exports = new ServerConfig()
  .apply(defaults)
  .loader("babel", ".js", {
    exclude: /node_modules/,
    query: babel,
  })
  .toWebpack()
;
```

**Comment by ericclemmons** [comment]
Wow.  Having `.babelrc` and `babel-loader` both is a PITA.

Until ericclemmons/npm-install-webpack-plugin#57 is resolved, I think the best practice should be:

- `.babelrc` with `es2015-webpack` that's specific for the builds.
- ES5 version for the `webpack.config.js` files.

**Comment by ericclemmons** [comment]
And of course, now I realize that I need to have the API work entirely different.

- The base API (e.g. `.entry`, `.loader`, etc.) should not have **any extra features** such as adding hot plugins, `DefinePlugin`, etc.
- The base API should be created via `.api(reducers)` (merged into default reducers) which should really just create a fluent interface for building up the history.
- The reducers themselves should export a `terse` and `webpack` reducer.
- The reducers will have access to the full state tree, but **should normally only operate on the part it's named after**. (e.g. `entry.terse(...)` would modify `state.entry` accordingly, but possibly read from `state.env`.

**Comment by ericclemmons** [comment]
Sorry for how much is happening here.

- Moved from `class` to an entirely immutable, functional approach.
- Went out of town for nearly two weeks.
- Architecturally decisions between features & reducers knowing interdependencies (nope).
- Repeating examples to ensure desired output is created.

So, here's a sneak peak:

```js
// webpack.config.client.js
var api = require("@terse/webpack").api()
  .entry("./src/client/js")
  .loader("babel", ".js", { exclude: /node_modules/ })
;

// See the normalized, serializable state of the api
// (this is what the reducers operate on to generate the webpack config)
console.log(api.getState().toString());

// Config for webpack
module.exports = api.getConfig();

// Or, if you want to copy/paste it into your file so there's no magic
console.log(api.getConfig().toString());
```

**Comment by ericclemmons** [comment]
Ok, so I think the best path to ensure this all works as expected is:

- [ ] Test all features.
- [ ] Test all reducers.
- [ ] Get a the "kitchen sink" example functioning.
- [ ] Port this back for use in the work project.
- [ ] Fix any remaining bugs.
- [ ] Merge this crap & move on.

**Comment by ericclemmons** [comment]
@insin I wanted to tip of you off to this project.  Activity is wrapping up on it very soon for v1, so here's the synopsis:

- The "best" way today to merge webpack configs means _deep-merging objects_.  This is complicated to say the least, and when it comes down to adding additional entries for, say, HMR, you have to support various object schemas.
- This project came from a work project that tried to do smart object merging.  We learned the hard-way that **object-merging is poor architecture** and doesn't scale, especially when trying to decipher how the final config is made.
- The architecture decisions of this project are:
  - A **fluent, gulp-like API interface** for defining the _features_ of a config (e.g. `.entry`, `.alias`, `.hot`, `.autoinstall`).
  - The API internally **builds an immutable history** so that you can build `defaults` and then build the API on top of it (without mutating the original config).  (Think of this like replaying Flux "actions".)
  - The API is used primarily for building a state object (via `.getState()`) internally.  **This is meant to describe the webpack features in a single, standardized way**.  This is important because...
  - The actual webpack config is created via `.getConfig()`, where the **state is passed through reducers** to create `entry`, `module`, `resolve`, `plugins`, etc. based on this state object.
  - The core design decision also allows for **having an escape hatch via `.getConfig().toString()`, which outputs a copy/paste-able webpack config**.  This, to me, is crucial for ditching `@terse/webpack` when you want to get down to the "metal", or get rid of any perceived magic.

Initially, this project can be used as nearly a 1-to-1 replacement for the config (with less confusion about object formatting), as can be seen here:
> https://github.com/ericclemmons/terse-webpack/tree/v1/test/fixtures/examples/kitchen-sink

But very soon it'll be easiest to say:

```js
module.exports = require("@terse/webpack").presets.react().target("web");
```

**Comment by insin** [comment]
Haven't had time to take a proper look under the hood, but this sounds amazing. Defaults, standardised way to change config, escape hatch :+1: :+1: :+1: 

Particularly interested in checking out what you do with plugins.

**Pull request merged**
